### ISSUE TITLE
Second developer?

### ISSUE THREAD

**Issue by JohnAD** [SkyVault/CoralFramework#1]
@SkyVault ,

Interested in a second developer on your new Framework?

My background is in Python, network engineering, assembler, and C. (Also in AI, startups, and woodworking, but those don't really apply here :)  ).

I'm just starting to investigate `nim`.

As it happens, I've already written a Android game in Python with the Kivy framework and managed to get it working on Google Play. Because of size and performance issues, I've been looking for a new platform and language to convert the app to. (Among other things, my Negamax AI algorithm barely runs fast enough in Python on a typical mobile device. I even came up with a non-recursive version of it.)

And, I also have a background in technical writing; so I'm happy to add to the documentation quite at bit.

So, what is your vision for CoralFramework?

I already like that you are focusing on 2D specifically. To quote Einstein: “Everything should be as simple as it can be, but not simpler”

If curious, details about the app I want to "translate" to nim:

  * [Entry on Google Play](https://play.google.com/store/apps/details?id=design.purplesquirrel.mancala)
  * [My video series about the programming (I'm known as **needless process** on YouTube)](https://www.youtube.com/playlist?list=PL6RpFCvmb5SEW1VVM9j3e0R7G5akKGu19)
  * [GitHub repo of source/assets](https://github.com/PurpleSquirrelGames/MancalaGameApp)
  * [Project detail on Maker Redux](https://www.makerredux.com/ahx2)

**Comment by JohnAD** [comment]
@SkyVault 

My offer to help still stands, but I'm going to be trying out the nim/Godot bindings next. Essentially, Godot is an existing open source game engine that supports both c and it's own proprietary language. The bindings in 3.0 allow other languages that support c-style calling to be used as well. Should be interesting.

**Comment by SkyVault** [comment]
Hey John, I really like the Godot engine and I think its really great that there are Nim bindings for it. Its something that want to look into later. As for this project, First off thank you for the offer. I don't feel comfortable quite yet having a second developer, the project is very early on in development and I've been making quite a few changes that will break the current API, but later on once things are more solid I will for sure be looking for help. My goal for this project is for it to be a very simple and great way to prototype and to create the games. I am very inspired by a framework called Love2D, it has a very simple API that makes sketching out projects very easy and intuetive.
